class HospitalRunner{
	public static void main(String arg[]){
		System.out.println("Hospital got invoked:");
		Hospital ref=new Hospital();
		ref.docoterId=1;
		ref.name="kushi";
		ref.gender="female";
		ref.qualification="mbbs";
		ref.noOfAdminStaff=11;
		System.out.println("the id og the docoter is "+ref.docoterId);
		System.out.println("the name of the docoter is"+ref.name);
		System.out.println("the gender of the docoter is:"+ref.gender);
		System.out.println("the qualification of the docoter is:"+ref.qualification);
		System.out.println("the noOfAdminStaff inthe hospital are:"+ref.noOfAdminStaff);
		Hospital ref1=new Hospital();
		ref1.docoterId=2;
		ref1.name="kurnal";
		ref1.gender="male;
		ref1.qualification="MD";
		ref1.noOfAdminStaff=12;
		System.out.println("the id og the docoter is "+ref1.docoterId);
		System.out.println("the name of the docoter is"+ref1.name);
		System.out.println("the gender of the docoter is:"+ref1.gender);
		System.out.println("the qualification of the docoter is:"+ref1.qualification);
		System.out.println("the noOfAdminStaff inthe hospital are:"+ref1.noOfAdminStaff);
		Hospital ref2=new Hospital();
		ref2.docoterId=3;
		ref2.name="pandey";
		ref2.gender="male";
		ref2.qualification="DBA";
		ref2.noOfAdminStaff=13;
		System.out.println("the id og the docoter is "+ref2.docoterId);
		System.out.println("the name of the docoter is"+ref2.name);
		System.out.println("the gender of the docoter is:"+ref2.gender);
		System.out.println("the qualification of the docoter is:"+ref2.qualification);
		System.out.println("the noOfAdminStaff inthe hospital are:"+ref2.noOfAdminStaff);
		Hospital ref3=new Hospital();
		ref3.docoterId=4;
		ref3.name="janavi";
		ref3.gender="female";
		ref3.qualification="JD";
		ref3.noOfAdminStaff=14;
		System.out.println("the id og the docoter is "+ref3.docoterId);
		System.out.println("the name of the docoter is"+ref.name);
		System.out.println("the gender of the docoter is:"+ref3.gender);
		System.out.println("the qualification of the docoter is:"+ref3.qualification);
		System.out.println("the noOfAdminStaff inthe hospital are:"+ref3.noOfAdminStaff);
		Hospital ref4=new Hospital();
		ref4.docoterId=5;
		ref4.name="Reena";
		ref4.gender="female";
		ref4.qualification="Do";
		ref4.noOfAdminStaff=15;
		System.out.println("the id og the docoter is "+ref4.docoterId);
		System.out.println("the name of the docoter is"+ref4.name);
		System.out.println("the gender of the docoter is:"+ref4.gender);
		System.out.println("the qualification of the docoter is:"+ref4.qualification);
		System.out.println("the noOfAdminStaff inthe hospital are:"+ref4.noOfAdminStaff);
		Hospital ref5=new Hospital();
		ref5.docoterId=6;
		ref5.name="rahul";
		ref5.gender="male";
		ref5.qualification="PHD";
		ref5.noOfAdminStaff=16;
		System.out.println("the id og the docoter is "+ref5.docoterId);
		System.out.println("the name of the docoter is"+ref5.name);
		System.out.println("the gender of the docoter is:"+ref5.gender);
		System.out.println("the qualification of the docoter is:"+ref5.qualification);
		System.out.println("the noOfAdminStaff inthe hospital are:"+ref5.noOfAdminStaff);
		Hospital ref6=new Hospital();
		ref6.docoterId=7;
		ref6.name="dohni";
		ref6.gender="male";
		ref6.qualification="MMBD;
		ref6.noOfAdminStaff=11;
		System.out.println("the id og the docoter is "+ref6.docoterId);
		System.out.println("the name of the docoter is"+ref6.name);
		System.out.println("the gender of the docoter is:"+ref6.gender);
		System.out.println("the qualification of the docoter is:"+ref6.qualification);
		System.out.println("the noOfAdminStaff inthe hospital are:"+ref6.noOfAdminStaff);
		Hospital ref7=new Hospital();
		ref7.docoterId=8;
		ref7.name="Sreyanka";
		ref7.gender="female";
		ref7.qualification="mbbs";
		ref7.noOfAdminStaff=11;
		System.out.println("the id og the docoter is "+ref7.docoterId);
		System.out.println("the name of the docoter is"+ref7.name);
		System.out.println("the gender of the docoter is:"+ref7.gender);
		System.out.println("the qualification of the docoter is:"+ref7.qualification);
		System.out.println("the noOfAdminStaff inthe hospital are:"+ref7.noOfAdminStaff);
		Hospital ref8=new Hospital();
		ref8.docoterId=9;
		ref8.name="kushi";
		ref8.gender="female";
		ref8.qualification="mbbs";
		ref8.noOfAdminStaff=11;
		System.out.println("the id og the docoter is "+ref8.docoterId);
		System.out.println("the name of the docoter is"+ref8.name);
		System.out.println("the gender of the docoter is:"+ref8.gender);
		System.out.println("the qualification of the docoter is:"+ref8.qualification);
		System.out.println("the noOfAdminStaff inthe hospital are:"+ref8.noOfAdminStaff);
		
	}


}