class Phone{
	public static void main(String mobile[]){
		System.out.println("12 GB RAM | 256 GB ROM(Inbuilt Memory) | Not Expandable | Dual SIM (Nano-SIM, dual stand-by) | RAM Type : LPDDR5 | Storage Type : UFS 3.1 | OTG Support || SIM1: Nano, SIM2: Nano | Network : 5G Connectivity on Both SIM Slots | Dual VoLTE(4G) | Wi-Fi 6; BT 5.3; NFC | Type C OTG Supportable | Type C Fast Charging Tecnology Support | Type C Earphone Support.");
		System.out.println("17.02 cm (6.7 inch) Full HD+ OLED Bezel-less with punch-hole || Flexible LTPO AMOLED Display with Refresh Rate of (1 Hz - 120 Hz) || Corning Gorilla Glass 5 Protection, HDR10+ & SGS Low Blue Light, 1,000,000:1 Contrast Ratio, 1000 nits 1600 nits, 240Hz Touch Sampling Rate, Haptic Touch Motor. || Now bigger and brighter, Phone (2) can intuitively adapt its 120 Hz refresh rate to preserve power when you're not on your phone. A killer display that doesn’t murder battery life.");
		System.out.println("Qualcomm Snapdragon 8+ Gen 1 || Octa Core Processor || Primary Clock Speed : 3 GHz | Secondary Clock Speed : 2.5 GHz | Tertiary Clock Speed : 1.8 GHz || This smartphone is equipped with the Snapdragon 8+ Gen 1 chipset to deliver an incredibly fast performance. Upgraded chipset. A power move | Phone (2) boasts an 80% improvement on performance over its predecessor. Now with rapid speed, the best in-house heat management, advanced camera capabilities. And so much more.");
		System.out.println("50 MP(OIS) +50MP Dual Camera Setup | 32MP Front Camera || Rear camera: Wide (main): 50 MP, Aperture Value of f/1.9, 24mm, 1/1.56");
		System.out.println("4700 mAh Lithium ion Battery || 45W Fast Charging; USB Type-C port || A battery that keeps going On and on and on and on, Get more power, faster. At 4,700 mAh, Phone (2) houses our longest lasting battery yet. Charge fully in just 55 minutes. Compatible with 15W Qi wireless charging. Phone (2) also doubles as a 5W wireless charger so you can power accessories like Ear (2) on-the-go.");
		System.out.println("In Disolay Fingerprint reader | stereo speakers. Phone (2) Designed with impressive features and a myriad of thought processes put together, this phone takes you to the next-level of interaction, thus allowing for a more focussed space. || Glass front (Gorilla Glass 5), glass back (Gorilla Glass), aluminum frame. || Multiple LED lights on the back (notifications, charging progress, camera fill light) IP54 - splash, water and dust resistant || Ruggedness : Dust proof");
		System.out.println(" Android 13 || NOTHING OS 2.0 || This monochrome smartphone is smooth, quick and offers an intuitive experience with 15% faster app launch time. You also get up to three years of OS upgrades. Customised widgets are interesting features of this phone that includes clock, photos, weather, etc. The Quick setting option on this phone lets u quickly navigate among apps and features. U can access information directly from your home screen from apps such as Weather and Nothing X.");
		System.out.println("The Most Beautiful & Interesting Feature of Nothing - Glyph Interface. an improved technology where you are actually using ur phone without being on your phone. U get to set different light and sound sequences for each and every contact you have. This light and sound sequence is also applicable for notifications. You also get Glyph composer where you can invoke different colours of light and sound combinations and create a unique Glyph ringtone.");
		System.out.println("Network Type : 5G, 4G LTE, UMTS, GSM | Supported Networks : 5G, 4G, 3G, 2G | Wi-Fi 6, 802.11 a/b/g/n/ac/ax, (2.4 GHz | 5 GHz Dual Band), 2x2 MIMO and MU-MIMO, Wi-Fi Direct, Hotspot | v5.3 Bluetooth Support | NFC | GPS | Wireless Charging | Face Unlock | In-Display Fingerprint Lock");
		System.out.println("4k @60fps Video Recording | Full HD Recording | HD Video Recording | Resolution Rear: 4K (at 60fps), Live HDR (4K (at 30 fps)), 1080p (at 30 fps/60 fps), Slow-Mo (480 fps) | Front: 1080p (60 fps), Live HDR (1080p (at 30 fps))");
		System.out.println("The Nothing Phone (2) 5G redefines mobile innovation with its unique design and powerful performance. Featuring a 6.7-inch LTPO OLED AMOLED display, it delivers ultra-smooth visuals with vibrant colors and deep contrast, ensuring an exceptional viewing experience. ");
		System.out.println("Powered by the Qualcomm Snapdragon 8+ Gen 1 processor, this phone provides lightning-fast performance, handling gaming, multitasking, and heavy apps effortlessly. ");
		System.out.println("Capture stunning photos with the 50 MP dual rear cameras with OIS, delivering clear, detailed shots in all lighting conditions, while the 32 MP front camera ensures crisp and vibrant selfies.");
		System.out.println("The 4700 mAh battery keeps you powered throughout the day, with 45W fast charging taking you from 0 to 100% in just 55 minutes, plus wireless and reverse wireless charging for added convenience.");
		System.out.println("With Nothing OS, a clean and seamless Android experience awaits, free from unnecessary bloatware. The Glyph Interface on the transparent back offers a futuristic way to customize notifications, control features, and express your style");
		System.out.println("Durability is enhanced with Corning Gorilla Glass and an IP54 rating for protection against dust and splashes. Stay connected with 5G, Wi-Fi 6, Bluetooth 5.3, and NFC, ensuring fast and reliable connections. With ample RAM and storage, you’ll have all the space you need for apps, photos, and games.");
		System.out.println("Its stereo speakers provide immersive sound for gaming and entertainment. The Nothing Phone (2) 5G is the perfect fusion of innovation, performance, and style, offering a truly next-gen smartphone experience for those who want to stand out.");
		System.out.println("mmersive Stereo Sound – Enjoy a truly immersive audio experience with dual stereo speakers tuned for rich sound output. Whether you’re watching movies, playing games, or streaming music, the phone delivers deep bass and clear highs. The Dolby-enhanced sound system ensures spatial audio-like quality, making it perfect for both casual listeners and audiophiles who crave excellent sound on the go");
		System.out.println("Smart Battery Optimization – The Nothing Phone (2) houses a powerful 4700 mAh battery designed for all-day use. With adaptive power management and 45W fast charging, you can go from zero to 100% in just 55 minutes. It also supports 15W wireless charging and 5W reverse wireless charging, letting you power accessories on the go. Optimized for battery longevity, the phone ensures fewer charging cycles, keeping it durable over time., ");
		System.out.println("dvanced Heat Management – The Nothing Phone (2) comes with cutting-edge heat management to ensure peak performance during heavy tasks like gaming or 4K video recording. The advanced cooling system prevents overheating while maintaining consistent speeds. Paired with the Snapdragon 8+ Gen 1 chipset, this ensures your phone stays cool and responsive, offering a reliable experience without throttling performance., ");	
	}


}